config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    passwords: 'users/passwords',
    omniauth_callbacks: 'users/omniauth_callbacks'
  }
  
  # posts
  resources :posts

  # users
  resources :users, only: [:show, :edit]

  # likes
  resources :likes, only: [:create, :destroy]

  # comments
  resources :comments, only: [:create]
  
  root to: 'posts#index'
  post 'like_comment', to: 'posts#like_comment', as: "like_comment"
  post 'like_post', to: 'posts#like_post', as: "like_post"
  post 'add_comment', to: 'posts#add_comment', as: "add_comment"
  post 'add_friend', to: 'users#add_friend', as: "add_friend"
  post 'confirm_friend', to: 'users#confirm_friend', as: "confirm_friend"
  get 'search_friends', to: 'users#search_friends', as: 'search_friends'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :omniauthable, omniauth_providers: %i[facebook]

  has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy

  has_many :friendships
  has_many :inverse_friendships, class_name: 'Friendship', foreign_key: 'friend_id'

  validates :first_name, :last_name, :location, presence: true

  def friends
    friends = []
    friendships.each { |friendship| friends << friendship.friend if friendship.acepted }
    inverse_friendships.each { |friendship| friends << friendship.user if friendship.acepted }
    friends.compact
  end

  # Users who have yet to confirme friend requests
  def pending_friends
    friendships.map { |friendship| friendship.friend unless friendship.acepted }.compact
  end

  def unnacepted_friend_requests
    friends = []
    inverse_friendships.each { |request| friends << request.user unless request.acepted }
    friends
  end

  # Users who have requested to be friends
  def friend_requests
    inverse_friendships.map { |friendship| friendship.user unless friendship.acepted }.compact
  end

  def confirm_friend(user)
    friendship = inverse_friendships.find { |friend| friend.user == user }
    friendship.acepted = true
    friendship.save
  end

  def friend?(user)
    friends.include?(user)
  end

  def search_friends(current_user)
    User.all.map { |user| user unless friend?(user) || current_user == user }.compact
  end

  def self.from_omniauth(auth)
    password = Devise.friendly_token[0, 20]
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.password = password
      user.password_confirmation = password
      user.first_name = 'Mr '
      user.last_name = auth.info.name
      user.location = 'Unknown'
      # If you are using confirmable and the provider(s) you use validate emails,
      # uncomment the line below to skip the confirmation emails.
      # user.skip_confirmation!
    end
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    @user = User.from_omniauth(request.env['omniauth.auth'])

    if @user.persisted?
      sign_in_and_redirect @user, event: :authentication
      set_flash_message(:notice, :success, kind: 'Facebook') if is_navigational_format?
    else
      session['devise.facebook_data'] = request.env['omniauth.auth']
      redirect_to new_user_registration_url
    end
  end

  def failure
    redirect_to root_path
  end
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up, keys: %i[first_name last_name location])
  end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController < ApplicationController
  before_action :set_user, only: %i[show edit search_friends]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @posts = @user.posts.order(updated_at: :desc)
    @can_request = can_request
  end

  # GET /users/1/edit
  def edit; end

  def search_friends
    @per_confirm_friends = @user.friend_requests.compact
    @per_request_friends = @user.search_friends(@user)
    @can_request = can_request
  end

  def add_friend
    friend = current_user.friendships.build(friend_id: params[:id], acepted: false)
    if friend.save
      redirect_back fallback_location: current_user, notice: 'You requested a frienship!'
    else
      redirect_to current_user, alert: 'You already are friend!'
    end
  rescue StandardError => e
    print e
    redirect_back fallback_location: current_user, alert: 'There was a problem requesting this!'
  end

  def confirm_friend
    friend = User.find(params[:id])
    if current_user.confirm_friend(friend)
      redirect_back fallback_location: current_user, notice: 'You acepted a frienship!'
    else
      redirect_to current_user, alert: 'You can not accept this friend!'
    end
  rescue StandardError => e
    print e
    redirect_back fallback_location: current_user, alert: 'There was a problem requesting this!'
  end

  private

  def can_request
    i_did_not_requested = Friendship.where('friend_id = ? AND user_id = ?', current_user.id, @user.id).none?
    friend_did_not_requested = Friendship.where('friend_id = ? AND user_id = ?', @user.id, current_user.id).none?
    not_friend = current_user.friend?(@user) == false
    i_did_not_requested && friend_did_not_requested && not_friend
  end

  # Use callbacks to share common setup or constraints between actions.
  def set_user
    @user = User.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def user_params
    params.require(:user).permit(:first_name, :last_name, :location)
  end
end

app/helpers/users_helper.rb
# frozen_string_literal: true

module UsersHelper
end

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :email %>
    <%= form.email_field :email, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :first_name %>
    <%= form.text_field :first_name, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :last_name %>
    <%= form.text_field :last_name, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :location %>
    <%= form.text_field :location, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :password %>
    <%= form.password_field :password, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :password_confirmation %>
    <%= form.password_field :password_confirmation, class: "form-control" %>
  </div>

  <div class="actions">
    <%= form.submit class: "btn btn-danger" %>
  </div>
<% end %>

app/views/users/edit.html.erb
<div class="container py-4">
<h1>Editing <%= @user.first_name%></h1>
<hr>
<%= render 'form', user: @user %>
<hr>
<%= link_to 'To User', @user %>
</div>

app/views/users/index.html.erb
<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Location</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= "#{user.first_name} #{user.last_name}" %></td>
        <td><%= user.email %></td>
        <td><%= user.location %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_session_path %>

app/views/users/search_friends.html.erb
<div class="row">
  <div class="col-md-3">
  </div>
  <div class="col-md-6 gedf-main">
  <div class="card gedf-card">
    <div class="card-header">
        <h3>Respond to Your Friend Requests</h3>
    </div>
    <div class="card-body list-group">
        <% if @per_confirm_friends.count > 0 %>
            <% @per_confirm_friends.each do |request| %>
                <div class="list-group-item list-group-item-action">
                    <a href="/users/<%= request.id  %>" class= "d-flex">
                        <%= gravatar_tag  request.email, :size => 40, :html => { :class => "img rounded-circle" } %> 
                        <p class="mx-3">
                            <%= "#{ request.first_name} #{request.last_name} on #{request.created_at.to_time.strftime('%B %e at %l:%M %p')}" %>
                        </p>
                    </a>
                    <%= button_to 'Confirm', confirm_friend_url(id: request.id), class: "btn btn-warning float-right" %>
                </div>
            <% end %> 
        <% else %>
            <h4>No more friend request! Go and talk with your friends!</h4>
            <%= link_to posts_url do%>
                <%= image_tag("bullhorn.png", size: 64, alt: "timeline") %>
                Your timeline
            <% end %>
        <% end %>
    </div>
  </div>
  <div class="card gedf-card">
  <div class="card-header">
        <h3>People You May Know</h3>
    </div>
    <div class="card-body list-group">
        <% if @per_request_friends.count > 0 %>
            <% @per_request_friends.each do |user| %>
                <div class="list-group-item list-group-item-action">
                    <a href="/users/<%= user.id  %>" class= "d-flex">
                        <%= gravatar_tag  user.email, :size => 40, :html => { :class => "img rounded-circle" } %>
                        <p class="mx-3">
                            <%= "#{ user.first_name} #{user.last_name} on #{user.created_at.to_time.strftime('%B %e at %l:%M %p')} " %>
                        </p>
                    </a>
                </div>
            <% end %>
        <% else %>
            <h4>Invite Friends to our Platform!</h4>
        <% end %>
    </div>
  </div>
  </div>
  <div class="col-md-3">
  </div>
</div>

app/views/users/show.html.erb
<div class="container emp-profile">
  <div class="row">
    <div class="col-md-3">
        <div class="profile-img">
            <%= gravatar_tag @user.email, :size => 200 %>
        </div>
    </div>
    <div class="col-md-7">
        <div class="profile-head">
          <h5>
              <%= "#{@user.first_name} #{@user.last_name}" %>
          </h5>
          <ul class="nav nav-tabs" id="myTab" role="tablist">
              <li class="nav-item">
                  <a class="nav-link active" id="home-tab" data-toggle="tab" href="#home" role="tab" aria-controls="home" aria-selected="true">Friends</a>
              </li>
              <li class="nav-item">
                  <a class="nav-link" id="profile-tab" data-toggle="tab" href="#profile" role="tab" aria-controls="profile" aria-selected="false">Timeline</a>
              </li>
          </ul>
        </div>
    </div>
    <div class="col-md-2">
      <% if current_user.id == @user.id %>
        <%= link_to 'Edit', edit_user_path(@user), class: "btn btn-primary" %>
      <% else %>
        <% if @can_request %>
          <%= button_to 'Request friend', add_friend_path(id: @user.id), class: "btn btn-info" %>
        <% else %>
            <button class="btn btn-light disabled">✔ Request Sent</button>
        <% end %>
      <% end %>
    </div>
  </div>
  <div class="row">
      <div class="col-md-4">
          <div class="profile-work">
              <p>User Id: <b><%= @user.id%></b></p>
              <p>Email: </p>
              <p><b><%= @user.email%></b></p>
              <p>First Name</p>
              <p><b><%= @user.first_name %></b></p>
              <p>Last Name</p>
              <p><b><%= @user.last_name %></b></p>
              <p>Location</p>
              <p><b><%= @user.location %></b></p>
          </div>
      </div>
      <div class="col-md-8">
          <div class="tab-content profile-tab" id="myTabContent">
              <div class="tab-pane fade show active" id="home" role="tabpanel" aria-labelledby="home-tab">
                <% if @user.friends.count > 0  %>
                  <div class="list-group">
                  <h3>Friends</h3>
                    <% @user.friends.each do |friend| %>
                      <% if friend != nil %>
                        <a href="/users/<%= friend.id  %>" class= "list-group-item list-group-item-action">
                          <%= gravatar_tag  friend.email, :size => 40, :html => { :class => "img-thumbnail rounded-circle" } %>
                          <%= "#{ friend.first_name} #{friend.last_name}" %>
                        </a> 
                      <% end %>
                    <% end %>
                  </div>
                <% else %>
                  <% if @user == current_user %>
                    <%= link_to search_friends_url(id: current_user.id), class:"link" do%>
                      <%= image_tag("search.png", size: 64, alt: "search") %>
                      Find Friends  
                    <% end %>
                  <% else %>
                    <% if @can_request %>
                      <%= button_to 'Request friend', add_friend_path(id: @user.id), class: "btn btn-info" %>
                    <% else %>
                      <button class="btn btn-light disabled">✔ Request Sent</button>
                    <% end %>
                  <% end %>
                <% end %>

                <% if current_user.id == @user.id && @user.friend_requests.count > 0  %>
                  <div class="list-group">
                  <h3>Pending Friends</h3>
                    <% @user.friend_requests.each do |friend| %>
                      <% if friend != nil %>
                        <div class="list-group-item list-group-item-action">
                          <a href="/users/<%= friend.id  %>" class="d-flex">
                            <%= gravatar_tag  friend.email, :size => 40, :html => { :class => "img-thumbnail rounded-circle" } %>
                            <%= "#{ friend.first_name} #{friend.last_name} at #{friend.created_at.to_time.strftime('%B %e at %l:%M %p')} " %>
                          </a>
                          <%= button_to 'Confirm', confirm_friend_url(id: friend.id), class: "btn btn-warning float-right" %>
                        </div>
                      <% end %>
                    <% end %>
                  </div>
                <% end %>
              </div>
              <div class="tab-pane fade" id="profile" role="tabpanel" aria-labelledby="profile-tab">  
                <% if @posts.count > 0 %>
                  <h4 class="text-info mt-2"><%= "#{@user.first_name}\'s posts" %></h4>
                  <div class="card-columns">
                    <% @posts.each do |post| %>
                    <div class="card">
                      <% if post.image_path.length > 0 %>
                        <%= link_to post do %>
                          <img class="card-img-top" src="<%= post.image_path%>" alt="image">
                        <% end %>
                      <% end %>
                      <div class="card-body">
                        <div class="float-right">
                            <% if current_user.id == @user.id %>
                              <div class="dropdown">
                                  <button class="btn dropdown-toggle" type="button" id="gedf-drop1" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                      ⋮
                                  </button>
                                  <div class="dropdown-menu dropdown-menu-right" aria-labelledby="gedf-drop1">
                                      <div class="h6 dropdown-header">More</div>
                                      <%= link_to 'Edit', edit_post_path(post), class: "dropdown-item" %>
                                      <%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' }, class:"dropdown-item" %>
                                  </div>
                              </div>
                            <% end %>
                          </div>
                        <div class="text-muted h7 mb-2"> <i class="fa fa-clock-o"></i><%= post.updated_at.to_time.strftime('%B %e at %l:%M %p') %></div>
                        <p class="card-text"><%= post.body %></p>
                      </div>
                      <div class="card-footer d-flex">
                        <%= button_to like_post_url(user_id: current_user.id, id: post.id), class: 'btn round card-link' do%>
                            Likes: <%= image_tag("like.png", size: 28) %>
                            <sup class="card-link"><%= post.likes.from_post(post.id).count %></sup>
                          <% end %>

                          <%= link_to post, class: "btn round card-link" do %>
                            Comments: <%= image_tag("comments.png", size: 28, alt: "Comments") %>
                            <sup class="card-link"><%= post.comments.count %></sup>
                          <% end %>
                      </div>
                    </div>
                    <% end %>
                  </div>
                <% else %>
                  <% if @user == current_user %>
                    <h4 class="text-warning">Share with the world!:</h4>
                    <%= link_to new_post_path, class:"link" do%>
                      <%= image_tag("type.png", size: 64, alt: "search") %>
                      Create a Publication
                    <% end %>                
                  <% else %>
                    <h4 class="text-info">User have not post</h4>
                  <% end %>
                <% end %>
              </div>
          </div>
      </div>
  </div>        
</div>