config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    passwords: 'users/passwords',
    omniauth_callbacks: 'users/omniauth_callbacks'
  }
  
  # posts
  resources :posts

  # users
  resources :users, only: [:show, :edit]

  # likes
  resources :likes, only: [:create, :destroy]

  # comments
  resources :comments, only: [:create]
  
  root to: 'posts#index'
  post 'like_comment', to: 'posts#like_comment', as: "like_comment"
  post 'like_post', to: 'posts#like_post', as: "like_post"
  post 'add_comment', to: 'posts#add_comment', as: "add_comment"
  post 'add_friend', to: 'users#add_friend', as: "add_friend"
  post 'confirm_friend', to: 'users#confirm_friend', as: "confirm_friend"
  get 'search_friends', to: 'users#search_friends', as: 'search_friends'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/post.rb
# frozen_string_literal: true

class Post < ApplicationRecord
  belongs_to :user
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy

  validates :body, presence: true
end

app/controllers/posts_controller.rb
# frozen_string_literal: true

class PostsController < ApplicationController
  before_action :set_post, only: %i[show edit update destroy like_comment like_post add_comment]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all.order(updated_at: :desc)
  end

  # GET /posts/1
  # GET /posts/1.json
  def show; end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit; end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def like_post
    current_user.likes.build(post_id: @post.id)
    if current_user.save
      redirect_back fallback_location: root_path, notice: 'You liked a comment!.'
    else
      redirect_to root_path, alert: 'You already liked this post'
    end
  end

  def like_comment
    @post.likes.build(user_id: params[:user_id], comment_id: params[:comment_id]).save
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'You liked a comment!.' }
      format.js { render inline: 'location.reload();' }
    end
  end

  def add_comment
    @post.comments.build(comment_params).save
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'You added a comment!.' }
      format.js { render inline: 'location.reload();' }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_post
    @post = Post.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def post_params
    params[:post] = params if params[:post].nil?
    params.require(:post).permit(:user_id, :body, :image_path)
  end

  def comment_params
    params[:comment] = params if params[:comment].nil?
    params.require(:comment).permit(:body, :post_id, :user_id)
  end
end

app/helpers/posts_helper.rb
# frozen_string_literal: true

module PostsHelper
end

app/views/posts/_form.html.erb
<div class="card gedf-card">
    <div class="card-header">
        <ul class="nav nav-tabs card-header-tabs" id="myTab" role="tablist">
            <li class="nav-item">
                <a class="nav-link active" id="posts-tab" data-toggle="tab" href="#posts" role="tab" aria-controls="posts" aria-selected="true">Make
                    a publication</a>
            </li>
            
        </ul>
    </div>
    <div class="card-body">
      <%= form_with(model: post, local: true) do |form| %>
        <div class="tab-content" id="myTabContent">
            <div class="tab-pane fade show active" id="posts" role="tabpanel" aria-labelledby="posts-tab">
                <div class="form-group">
                  <%= form.text_area :body, class: "form-control" %>
                </div>
                <div class="form-group">
                  <%= form.text_field :image_path, class: "form-control", placeholder: "Link to image" %>
                </div>
            </div>
        </div>
        <%= form.hidden_field :user_id, value: current_user.id %>
        <div class="btn-toolbar justify-content-between">
            <div class="btn-group">
                <%= form.submit 'Submit', class: "btn btn-dark" %>
            </div>
        </div>
      <% end %>
    </div>

</div>

app/views/posts/edit.html.erb
<div class="container py-4">
<h1>Editing Post</h1>
<% if @post.errors.any? %>
    <div id="error_explanation">
    <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

    <ul>
    <% @post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
    <% end %>
    </ul>
    </div>
<% end %>
<%= render 'form', post: @post %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>
</div>

app/views/posts/index.html.erb
<div class="row">
  <div class="col-md-3">
    <div class="card">
      <%= link_to current_user, class: "card-body" do%>
          <div class="h5"><%= "#{current_user.first_name} #{current_user.last_name}" %></div>
          <div class="h7 text-muted"><%= current_user.email %></div>          
      <% end %>
      <ul class="list-group list-group-flush">
          <li class="list-group-item">
              <div class="h6 text-muted">Friends</div>
              <div class="h5"><%= current_user.friends.count %></div>
          </li>
          <li class="list-group-item">
            <%= link_to  "Edit Profile", edit_user_path(current_user)%>
          </li>
      </ul>
  </div>
</div>

<div class="col-md-6 gedf-main">
  <%= render 'form', post: @post %>
  <!-- CREATE Post /////-->

  <!--- \\\\\\\Posts-->
  <% @posts.each do |post| %>

    <div class="card gedf-card">
      <div class="card-header">
          <div class="d-flex justify-content-between align-items-center">
              <%= link_to post.user, class: "d-flex justify-content-between align-items-center" do%>
                <div class="mr-2">
                    <%= gravatar_tag post.user.email, :size => 45, :html => { :class => "img rounded-circle" } %>
                </div>
                <div class="ml-2">
                    <div class="h5 m-0">
                      <%= "by #{post.user.first_name} #{post.user.last_name}" %>
                    </div>
                    <div class="h7 text-muted">
                      <%= "#{post.user.email}" %>
                    </div>
                </div>
              <% end %>
              <div>
                <% if current_user == post.user %>
                  <div class="dropdown">
                      <button class="btn dropdown-toggle" type="button" id="gedf-drop<%= post.id%>" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                          ⋮
                      </button>
                      <div class="dropdown-menu dropdown-menu-right" aria-labelledby="gedf-drop<%= post.id%>">
                          <div class="h6 dropdown-header">More</div>
                          <%= link_to 'Edit', edit_post_path(post), class: "dropdown-item" %>
                          <%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' }, class:"dropdown-item" %>
                      </div>
                  </div>
                <% end %>
              </div>
          </div>
      </div>
      <% if post.image_path.length > 0 %>
        <%= link_to post do %>
          <img class="card-img-top" src="<%= post.image_path%>" alt="image">
        <% end %>
      <% end %>
      <div class="card-body">
          <div class="text-muted h7 mb-2"> <i class="fa fa-clock-o"></i><%= post.updated_at.to_time.strftime('%B %e at %l:%M %p') %></div>
          <p class="card-text">
              <%= post.body %>
          </p>
      </div>
      <div class="card-footer d-flex">
          <%= button_to like_post_url(user_id: current_user.id, id: post.id), class: 'btn round card-link', name: "Like" do%>
            <%= image_tag("like.png", size: 24, alt: "Likes") %>
            <sup class="badge badge-primary"><%= post.likes.from_post(post.id).count %></sup>
          <% end %>
          <%= link_to post, class: "btn round card-link" do %>
            <%= image_tag("comments.png", size: 24, alt: "Comments") %>
            <sup class="badge badge-primary"><%= post.comments.count %></sup>
          <% end %>
      </div>
    </div>
  <% end %>
</div>

<div class="col-md-3">
  <div class="card gedf-card">
      <div class="card-body">
          <h5 class="card-title">Some Ad</h5>
          <h6 class="card-subtitle mb-2 text-muted">Punchline</h6>
          <p class="card-text">Some quick example text to build on and make up the bulk of the
              ads's content.</p>
          <a href="#" class="card-link">link</a>
          <a href="#" class="card-link">Another link</a>
      </div>
  </div>
</div>

app/views/posts/new.html.erb
<div class="container py-4">
<h1>New Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Back', posts_path %>
</div>

app/views/posts/show.html.erb
<div class="container py-4">
<div class="card gedf-card">
      <div class="card-header">
    <div class="d-flex justify-content-between align-items-center">
              <%= link_to user_url(@post.user), class: "d-flex justify-content-between align-items-center" do%>
                <div class="mr-2">
                    <%= gravatar_tag @post.user.email, :size => 45, :html => { :class => "img rounded-circle" } %>
                </div>
                <div class="ml-2">
                    <div class="h5 m-0">
                      <%= "by #{@post.user.first_name} #{@post.user.last_name}" %>
                    </div>
                    <div class="h7 text-muted">
                      <%= "#{@post.user.email}" %>
                    </div>
                </div>
              <% end %>
              <div>
                <% if current_user == @post.user %>
                  <div class="dropdown">
                      <button class="btn dropdown-toggle" type="button" id="gedf-drop1" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                          ⋮
                      </button>
                      <div class="dropdown-menu dropdown-menu-right" aria-labelledby="gedf-drop1">
                          <div class="h6 dropdown-header">More</div>
                          <%= link_to '⚙ Edit', edit_post_path(@post), class: "dropdown-item" %>
                          <%= link_to '🚫 Destroy', @post, method: :delete, data: { confirm: 'Are you sure?' }, class:"dropdown-item" %>
                      </div>
                  </div>                  
                <% end %>
              </div>
          </div>
      </div>
      <% if @post.image_path.length > 0 %>
        <img class="card-img-top" src="<%= @post.image_path%>" alt="image">
      <% end %>
  <div class="card-body">
      <div class="text-muted h7 mb-2"> <i class="fa fa-clock-o"></i><%= @post.updated_at.to_time.strftime('%B %e at %l:%M %p') %></div>
      <p class="card-text">
          <%= @post.body %>
      </p>
      <div class="d-flex">
        <%= button_to like_post_url(user_id: current_user.id, id: @post.id), class: 'btn round card-link' do%>
            <%= image_tag("like.png", size: 28) %>
            <sup class="badge badge-primary"><%= @post.likes.from_post(@post.id).count %></sup>
          <% end %>

          <%= link_to @post, class: "btn round card-link" do %>
            <%= image_tag("comments.png", size: 28, alt: "Comments") %>
            <sup class="badge badge-primary"><%= @post.comments.count %></sup>
          <% end %>
      </div>
      <div>
        <%= form_with url: add_comment_path do |form| %>

        <%= form.hidden_field :user_id, value: current_user.id %>
        <%= form.hidden_field :id, value: @post.id %>
        <div class="form-group">
          <%= form.text_area :body, class: "form-control", placeholder: "Comment:" %>
        </div>
        <div class="actions">
          <%= form.submit "🗨 Comment", class: "float-right btn btn-info" %>
        </div>
        <% end %>
      </div>
  </div>
  <div class="card-footer">
    <% if @post.comments %>
      <ul class="list-group list-group-flush">
        <% @post.comments.each do |comment| %>
          <li class="list-group-item">
          <%= gravatar_tag comment.user.email, :size => 28, :html => { :class => "img rounded-circle" } %>
          <strong><%= "#{comment.user.first_name} #{comment.user.last_name}" %></strong><br>
          <%= comment.body%>
          </li>
        <% end %>
      </ul> 
    <% else %>
      No
    <% end %>
  </div>
</div>
<%= link_to 'Back', posts_path %>
</div>