config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    passwords: 'users/passwords',
    omniauth_callbacks: 'users/omniauth_callbacks'
  }
  
  # posts
  resources :posts

  # users
  resources :users, only: [:show, :edit]

  # likes
  resources :likes, only: [:create, :destroy]

  # comments
  resources :comments, only: [:create]
  
  root to: 'posts#index'
  post 'like_comment', to: 'posts#like_comment', as: "like_comment"
  post 'like_post', to: 'posts#like_post', as: "like_post"
  post 'add_comment', to: 'posts#add_comment', as: "add_comment"
  post 'add_friend', to: 'users#add_friend', as: "add_friend"
  post 'confirm_friend', to: 'users#confirm_friend', as: "confirm_friend"
  get 'search_friends', to: 'users#search_friends', as: 'search_friends'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>IrlaFacebook</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= favicon_link_tag asset_path('users.png') %>
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
      integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-expand-md navbar-dark bg-dark">
      <div class="container">
        <a class="navbar-brand" href="/">
        <%= image_tag("users.png", alt: "rss feed", size: 40) %>
        IRLA</a>
        <button class="navbar-toggler d-lg-none" type="button" data-toggle="collapse" data-target="#collapsibleNavId"
          aria-controls="collapsibleNavId" aria-expanded="false" aria-label="Toggle navigation"></button>
        <div class="collapse navbar-collapse" id="collapsibleNavId">
          <ul class="navbar-nav ml-auto mt-2 mt-lg-0">
            <% if user_signed_in? %>
            <li class="nav-item">
              <%= link_to user_path(current_user), class: "nav-link d-flex" do%>
                <%= gravatar_tag current_user.email, :size => 24, :html => { :class => "img rounded-circle" } %>
                <%=" #{current_user.first_name}"%>
              <% end %>
            </li>
            <li class="nav-item">
              <%= link_to  "Home", root_path, class:"nav-link" %>
            </li>
            <li class="nav-item">
              <%= link_to  "Find Friends", search_friends_url(id: current_user.id), class:"nav-link" %>
            </li>
            <li class="nav-item">
              <div class="dropdown">
                <button class="btn btn-link dropdown-toggle" type="button" id="gedf-drop-nav" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  <%= image_tag("notification.png", size: 24) %>
                  <% if current_user.unnacepted_friend_requests.count > 0 %>
                    <span class="badge badge-light"><%= current_user.unnacepted_friend_requests.count %></span>
                  <% end %>
                </button>
                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="gedf-drop-nav">
                    <div class="h6 dropdown-header">Notifications</div>
                      <% current_user.unnacepted_friend_requests.each do |requester| %>
                        <%= link_to current_user, class: "dropdown-item d-flex" do %>
                          <%= gravatar_tag requester.email, :size => 24, :html => { :class => "img rounded-circle" } %>
                          <%= " #{requester.first_name} #{requester.last_name} want to be your friend"%>
                        <% end %>
                      <% end %>
                </div>
              </div>
            </li>
            <li class="nav-item">
              <%= link_to  "Logout", destroy_user_session_path, method: :delete, class: "nav-link" %>
            </li>
            <% else%>
            <li class="nav-item">
              <%= link_to  "Sign In", new_user_session_path, class: "nav-link" %>
            </li>
            <li class="nav-item">
              <%= link_to  "Sign Up", new_user_registration_path, class: "nav-link" %>
            </li>
            <% end %>
          </ul>
        </div>
      </div>
    </nav>
    <div class="container-fluid gedf-wrapper py-4">
      <% if notice %>
      <div class="alert alert-info alert-dismissible fade show" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
        <strong><%= notice %></strong>
      </div>
      <% elsif alert %>
      <div class="alert alert-danger alert-dismissible fade show" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
        <strong><%= alert %></strong>
      </div>
      <% end %>

      <%= yield %>
    </div>

    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js"
      integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous">
    </script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
      integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous">
    </script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"
      integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous">
    </script>
  </body>
</html>